version: "3.3"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: taskdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  backend:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

