
name: Go CI
on:
  push:
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    # ジョブ内で実行する step を定義
    steps:
      # リポジトリからソースコードの取得
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.21.4
      - name: Run Test
        run: go test -v ./...
